language: node_js
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_install:
  - npm i -g npm@6
before_script:
  - npm run test
  - npm run lint
script:
  - npm run build
after_script:
  - npm run test:coverage
  - npm run test:coverage:report
after_success:
  - npm run semantic-release